# Generated by Django 3.2.8 on 2021-11-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField(default='https://www.facebook.com/')),
                ('twitter', models.URLField(default='https://twitter.com/')),
                ('flickr', models.URLField(default='https://www.flickr.com/')),
                ('pinterest', models.URLField(default='https://www.pinterest.com/')),
                ('googleplus', models.URLField(default='https://www.google.com/')),
                ('vimeo', models.URLField(default='https://vimeo.com/')),
                ('youtube', models.URLField(default='https://www.youtube.com/')),
                ('mail', models.CharField(default='mailto:sasha-mikayelyan@mail.ru', max_length=50)),
                ('number', models.CharField(default='(+374)93 66-85-03', max_length=30)),
                ('address', models.CharField(default='Armenia, Yerevan....', max_length=100)),
            ],
            options={
                'verbose_name_plural': '⚙ Site Contacts ⚙',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name_plural': '❓ Questions',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('autor', models.CharField(default='Moderator', max_length=100)),
                ('tegs', models.CharField(default='#News', max_length=300)),
                ('news_text', models.CharField(default='', help_text='News content', max_length=5000)),
                ('video_from_youtube', models.CharField(blank=True, default='', max_length=30)),
                ('image', models.ImageField(blank=True, default='News/featured_img2.jpg', upload_to='News')),
                ('uploading_time', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
                ('unlike', models.IntegerField(default=0)),
                ('number', models.CharField(default='#0', help_text='Please set the number of last news(unique)', max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsapp.category')),
            ],
            options={
                'verbose_name_plural': '📰 News',
            },
        ),
    ]
