# Generated by Django 3.2.8 on 2021-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20211118_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='AboutSite/about.jpg', upload_to='AboutSite')),
                ('about_us', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '📄 Categories'},
        ),
        migrations.AlterModelOptions(
            name='livenews',
            options={'verbose_name_plural': 'Live News 🎥'},
        ),
    ]
